### PR TITLE
Allow negative scales in advanced mode.

### PR DESCRIPTION
**Pull request by AdamNorberg**
Negative guidance scale factors give interesting results where the AI tries to create "the opposite" of your prompt. That seems fun to play with, so I think that should be possible in Advanced Mode. This CL extends the guidance scale slider into negative values in advanced mode.

### CODE REVIEW

**Comment by AdamNorberg** [comment]
This doesn't seem to work, it's acting like a positive value. I must not have paid attention to how parameters are passed to the script. Investigating.

**Comment by AdamNorberg** [comment]
Okay, I've worked out the bugs in *my* code but apparently the scripts getting called into promote "0" to "default" and reject negative numbers, even though those are perfectly valid scales in Stable Diffusion. ugh. all right, I guess I have another repo to patch...

**Comment by n00mkrad** [comment]
Maybe create an issue or PR in the lstein repo which I fork for this GUI

**Comment by n00mkrad** [comment]
You messed something up though, entering `15 > -70 : 1` results in it going from -70 to 15 instead of 15 to -70.

**Comment by AdamNorberg** [comment]
Fixing this issue now, look for another pull request soon. Sorry about the mess.

**Pull request merged**
