### PR TITLE
Compatibility fix.

### PR DESCRIPTION
**Pull request by xliee**
Fix an error that raises in systems where anaconda3 is already installed.

### CODE REVIEW

**Comment by n00mkrad** [comment]
Thanks, but shouldn't PYTHONHOME not have any effect, as I remove all existing PATH entries (except for WINDIR stuff) beforehand?

I will merge it anyway since it can't harm, just wondering if you know more about that.

**Comment by xliee** [comment]
For me its failing without the PYTHONHOME variable. It took me some hours to figure out, it may be because i already have the PYTHONHOME enviroment variable set to my computer anaconda installation and maybe the included conda version conflicts with it(?)

**Comment by xliee** [comment]
image

image

**Comment by n00mkrad** [comment]
Alright

**Comment by n00mkrad** [comment]
It does the opposite for me.

With your PR, I get the following pip error during dependency installation:

`ImportError: cannot import name 'text_encoding' from 'io' (unknown location)`

**Pull request merged**
