### PR TITLE
Other trash

### PR DESCRIPTION
**Pull request by ForserX**
I offer it as a repository of ready-made solutions. Of interest: app escale fixes on 2k and 4k monitors, preview box for generated images. There were a lot of buns for ONNX, but there were no resources left. Take it if something is interesting. I'll remove the repo in a few days.

### CODE REVIEW

**Comment by n00mkrad** [comment]
Oh shit woah

That's gonna be a bit painful to merge especially as I just did some refactoring

**Comment by n00mkrad** [comment]
I will look into this stuff asap.

Minor nitpick: "Pilot" is probably supposed to mean "Plot".

Also do you also have a fork of [the repo with the scripts](https://github.com/n00mkrad/stable-diffusion-cust) for ONNX etc?

**Comment by n00mkrad** [comment]
Where is your sd_onnx.py then?

**Comment by ForserX** [comment]
Can be collected from here: 
https://github.com/ForserX/StableDiffusionUI/blob/main/data/repo/diffusion_scripts/sd_onnx.py
https://github.com/ForserX/StableDiffusionUI/blob/main/data/repo/diffusion_scripts/sd_xbackend.py

**Pull request closed without merging**
